import type webpack from 'webpack';

// prefer loader-utils over self-implemented hash function to utilize caching + bulk hashing
import { getHashDigest } from 'loader-utils';

export default function (this: webpack.LoaderContext<unknown>) {
  const callback = this.async();
  const data = decodeURIComponent(this.resourceQuery.slice(1));

  try {
    // @ts-expect-error -- getHashDigest supports string & xxhash64
    const hash = getHashDigest(data, 'xxhash64', 'base62', 32);

    const css = `
    /*
     * dummy css generated by stylex-webpack
     * real css will be injected later directly to the module
     *
     * stylex rules: ${data}
     */
    .__stylex_dummy_${hash} {}`;

    callback(null, css);
  } catch (e) {
    callback(e as Error);
  }
}
